name: Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: Generate Coverage Report
      run: |
        python -m pip install -r requirements.txt
        python -m coverage -m run -m unittest discover
        python -m coverage xml
    
    - name: Upload to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
